baseURL = 'https://m-raharjo.github.io/'
languageCode = 'en-us'
title = 'Timboel'
[caches]
  [caches.getcsv]
    maxAge = 0
[security]
  [security.http]
    methods = ['GET']
    urls = ['https://docs.google.com/',
    'https://kirun.pttimboel.com/'
    ]
[taxonomies]
  category = 'categories'
  tag = 'tags'
  collection = 'collections'
